apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask-app
spec:
  type: NodePort                     # Load balancing across nodes
  selector:
    app: flask-app
  ports:
    - name: http
      port: 5000                     # Service port
      targetPort: 5000               # Container port
      nodePort: 30080                # Optional: fixed NodePort (30000â€“32767)